### ISSUE TITLE
voxels that have no event

### ISSUE THREAD

**Issue by kazus0222** [compneuro-da/rsHRF#52]
When I applied rsHRF for my data, the event number of some voxels is 0.
How are voxels without an event processed?

**Comment by danielemarinazzo** [comment]
It might happen, and in these cases of course no estimation is possible. You might want to check the signal for these voxels for anomalies though, since in z-scored "normal" BOLD data it should be possible to detect some events.

Hope this helps

**Comment by kazus0222** [comment]
Thanks for your reply. I’ m going to check my preprocess pipeline.
Could you please tell me for my reference how do you normalize the data with z-scoring.

**Comment by danielemarinazzo** [comment]
In matlab the command is zscore. It is already included in the code (it does not matter if you do it multiple times, provided you do it in the correct dimension).
