### ISSUE TITLE
temporal grid magnification >1 also for FIR?

### ISSUE THREAD

**Issue by danielemarinazzo** [compneuro-da/rsHRF#54]
Hi @sofievdbos and @guorongwu , I don't remember if we changed this. In the master branch of the python implementation this is allowed, on the other hand it's not here.
thanks!

**Comment by sofievdbos** [comment]
All Matlab HRF basis functions for which the grid magnification (`xBF.T`) can be set > 1 are included in the [rsHRF_estimation_temporal_basis.m](https://github.com/compneuro-da/rsHRF/blob/update/code/rsHRF_estimation_temporal_basis.m) function (so not for (s)FIR as far as I know).

**Comment by guorongwu** [comment]
not for FIR in rsHRF
