### ISSUE TITLE
tlb_cfg_rsHFR.m not loading

### ISSUE THREAD

**Issue by carciu** [compneuro-da/rsHRF#55]
Hello

hope to get some help 

I have Matlab R2015a, and try to install HRF, the install script works fine, no errors, however, loading SPM comes with this message and the toolbox does not appear in tools from the batch mode. Thank you for any help !

SPM12: v7771                                       20:45:33 - 05/03/2021
========================================================================
Initialising SPM                        :                   ..
Warning: Loading of older CAT12 segmentation versions was not successful and will be skipped.
Loading of toolbox /Applications/spm12/toolbox/rsHRF/tbx_cfg_rsHRF.m failed.
......done

SPM present working directory:
	/Users/

**Comment by guorongwu** [comment]
Hi carciu
can you edit tbx_cfg_rsHRF.m in the Matlab Editor window?
if the first line is:     ï»¿function HRFrs = tbx_cfg_rsHRF
please delete " ï»¿", and save it. then you can try to load SPM again: spm fmri

https://stackoverflow.com/questions/18845976/whats-%C3%AF-sign-at-the-beginning-of-my-source-file
