### ISSUE TITLE
Error use rsHRF_estimation_temporal_basis 

### ISSUE THREAD

**Issue by L202123** [compneuro-da/rsHRF#56]
I hope to get some help!
I've tried Job1 of the demo jobs, but failed. The error messages are shown below.
I just followed the rsHRF_manual_Matlab and don’t know how to solve the problem.
Thank you for any help !

Error use rsHRF_estimation_temporal_basis (line 34)
The source code for the parfor loop that attempted to execute the worker process could not be found (D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_estimation_temporal_basis.m)
In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_estimation_temporal_basis.m" (v4473), function "rsHRF_estimation_temporal_basis" at line 34.
In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_deconv_job.m" (???), function "rsHRF_deconv_job" at line 41.
In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF.m" (???), function "rsHRF" at line 113.
In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\tbx_cfg_rsHRF.m" (???), function "wgr_vox_ROI_rsHRF_conn" at line 884.
The following modules did not run:
Failed: Voxel-wise HRF deconvolution

**Comment by guorongwu** [comment]
> I hope to get some help!
> I've tried Job1 of the demo jobs, but failed. The error messages are shown below.
> I just followed the rsHRF_manual_Matlab and don’t know how to solve the problem.
> Thank you for any help !
> 
> Error use rsHRF_estimation_temporal_basis (line 34)
> The source code for the parfor loop that attempted to execute the worker process could not be found (D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_estimation_temporal_basis.m)
> In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_estimation_temporal_basis.m" (v4473), function "rsHRF_estimation_temporal_basis" at line 34.
> In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_deconv_job.m" (???), function "rsHRF_deconv_job" at line 41.
> In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF.m" (???), function "rsHRF" at line 113.
> In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\tbx_cfg_rsHRF.m" (???), function "wgr_vox_ROI_rsHRF_conn" at line 884.
> The following modules did not run:
> Failed: Voxel-wise HRF deconvolution

Hi, in this code (rsHRF_estimation_temporal_basis.m), you can change line 20 ('flag_parfor = 1'):   flag_parfor = 0;
it seems parfor did not work.

**Comment by L202123** [comment]
Thank you.
I have changed it,but it still doesn't work.&nbsp;
The error messege is shown in the figure.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "compneuro-da/rsHRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [compneuro-da/rsHRF] Error use rsHRF_estimation_temporal_basis  (#56)





  
I hope to get some help!
 I've tried Job1 of the demo jobs, but failed. The error messages are shown below.
 I just followed the rsHRF_manual_Matlab and don’t know how to solve the problem.
 Thank you for any help !
 
Error use rsHRF_estimation_temporal_basis (line 34)
 The source code for the parfor loop that attempted to execute the worker process could not be found (D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_estimation_temporal_basis.m)
 In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_estimation_temporal_basis.m" (v4473), function "rsHRF_estimation_temporal_basis" at line 34.
 In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF_deconv_job.m" (???), function "rsHRF_deconv_job" at line 41.
 In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\rsHRF.m" (???), function "rsHRF" at line 113.
 In file "D:\MATLAB\toolbox\spm12\toolbox\rsHRF\tbx_cfg_rsHRF.m" (???), function "wgr_vox_ROI_rsHRF_conn" at line 884.
 The following modules did not run:
 Failed: Voxel-wise HRF deconvolution
  
Hi, in this code (rsHRF_estimation_temporal_basis.m), you can change line 20 ('flag_parfor = 1'):   flag_parfor = 0;
 it seems parfor did not work.

**Comment by danielemarinazzo** [comment]
Thanks, I don't seem to find a figure in your message, can you please try again?
Also without the parfor loop it should be clearer to see where the error was, you can maybe just past the error message again.

**Comment by L202123** [comment]
Thanks
The error message is in the picture.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "compneuro-da/rsHRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [compneuro-da/rsHRF] Error use rsHRF_estimation_temporal_basis  (#56)





 
Thanks, I don't seem to find a figure in your message, can you please try again?
 Also without the parfor loop it should be clearer to see where the error was, you can maybe just paste the error message again.

**Comment by danielemarinazzo** [comment]
I am really sorry, there's no picture to be seen. You should be able to drag it in the text, as I am doing below

![rsHRF_logo](https://user-images.githubusercontent.com/5311102/116214423-f979f200-a746-11eb-828f-df92bd66230a.png)

or just send it by email.

thanks

**Comment by danielemarinazzo** [comment]
if you are replying to these messages from the email thread, and attaching pictures there, they will apparently be lost in the process

**Comment by L202123** [comment]
![841695AC@54AE5535 DACD8760 jpg_recompress](https://user-images.githubusercontent.com/83272968/116218989-aff8c980-a77d-11eb-93e2-54ce5d56ebfa.jpg)
I am really sorry for the mistake, and  thanks for your reminding. Now the picture is here.

**Comment by danielemarinazzo** [comment]
thanks a lot! Can you please run it again without the parfor, so we get to see exactly at which line the code breaks?

**Comment by L202123** [comment]
Thank you very much, I am not good at coding and can only use the rsHRF toolbox, but I will try my best. Maybe it will take some time. Thanks again!

**Comment by danielemarinazzo** [comment]
no problem, let us know if we can help.
If you open the SPM GUI, can you properly see the rsHRF plugin?

you can check the videos here https://www.youtube.com/watch?v=oPUc6iKQ7WE&list=PL_q40YXhtno0-H50OzYqtKBVIvo7vwOZg

For the moment you could just put the parfor flag to zero as suggested by @guorongwu amd paste the error message again.

**Comment by L202123** [comment]
![image](https://user-images.githubusercontent.com/83272968/116223607-47601b80-a782-11eb-9232-171207ac2c7c.png)
yes, I can see that and I will try again. Thanks fo the videos.

**Comment by L202123** [comment]
I have put the parfor flag to zero as suggested, but the error message is the same as before.

**Comment by danielemarinazzo** [comment]
so it still mentions a parfor loop? that should not be the case

**Comment by guorongwu** [comment]
Hi, 你可以直接弄一个临时会议（比如腾讯会议），共享一下你的屏幕，我可以远程协助一下解决这个问题。

**Comment by guorongwu** [comment]
can you also paste some data reading information before the error happened?
if the fMRI data was not at the same place in the Job1 demo, it will report an error.

**Comment by L202123** [comment]
非常感谢老师！为了避免耽误您的时间，我先进一步学习一下，多看看使用手册多试试，把问题汇总一下，到时候找您约时间，集中向您请教可以吗？

**Comment by guorongwu** [comment]
ok

**Comment by L202123** [comment]
Hi, the problem was solved without doing anything. It’s amazing. Maybe there was something wrong with the computer. Thanks a lot for your help. And I will learn more about the toolbox. Maybe there will be new problems and I will ask for help again. Thanks again.
