### ISSUE TITLE
About parametes

### ISSUE THREAD

**Issue by L202123** [compneuro-da/rsHRF#58]
Hi
I need some help. I'm confused by these parameters. I have learned the manual. In the manual, different jobs have different parameters. I don't know how to changes these parameters to get a best result.
Can you tell me how to set them?  Thanks a lot
![360截图20210612130928834](https://user-images.githubusercontent.com/83272968/121765823-3592d600-cb80-11eb-8e6e-88262ad07a4c.jpg)

**Comment by guorongwu** [comment]
microtime resolution: if you want to estimate HRF with the finer temporal resolution, set it >1
Threshold for event detection: it's the threshold for point process detection, I always do not change it.
K: we assume the amplitude of 'event' is always the 'local' maximum value (here is the information about how to define the local maximum)
temporal mask for event detection: you can add it when you want to delete some spurious events (such as time points with high head motion)

**Comment by L202123** [comment]
Thanks a lot for your reply.
And I also want to ask that how to set the "Microtime oneset"?
Is there any relationship between "Microtime oneset" and “Microtime resolution”?
Thanks

**Comment by guorongwu** [comment]
when you increase the temporal resolution (if Microtime resolution is k), each time point will become k time points, e.g. one of the first k time points should be selected as the (original) first time point, that's 'Microtime onset'. 
you can just set it as 1 if you do not know which is the best.

**Comment by L202123** [comment]
OK, I get it. 
Thank you very much.
